export const EXEC_COMMAND = 'EXEC_COMMAND';
export const KEYPAD_PRESS = 'KEYPAD_PRESS';
export const KEYBOARD_PRESS = 'KEYBOARD_PRESS';
export const TURN_OF_SCREEN = 'TURN_OF_SCREEN';
export const SET_PASSCODE = 'SET_PASSCODE';
export const LOCK_SAFE_DEPOSIT_BOX = 'LOCK_SAFE_DEPOSIT_BOX';
export const UNLOCK_SAFE_DEPOSIT_BOX = 'UNLOCK_SAFE_DEPOSIT_BOX';
export const SET_STATE = 'SET_STATE';